AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM Template for Applot Server Infrastructure

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5
    Runtime: python3.8
    MemorySize: 1536

Resources:
  # LAMBDAS
  UserManagementFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: components/lambdas/user_management/
      Handler: app.lambda_handler
      Policies:
        - AmazonDynamoDBFullAccess
      Events:
        CreateUser:
          Type: Api
          Properties:
            Path: /create_user
            Method: PUT
        EditUser:
          Type: Api
          Properties:
            Path: /edit_user
            Method: POST
        DeleteUser:
          Type: Api
          Properties:
            Path: /delete_user
            Method: DELETE
        AuthenticateUser:
          Type: Api
          Properties:
            Path: /auth_user
            Method: GET

  # DYNAMODB
  Accounts:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "Accounts"
      AttributeDefinitions:
        - AttributeName: "account_id"
          AttributeType: "S"
        - AttributeName: "email"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "account_id"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      GlobalSecondaryIndexes:
        - IndexName: "email_index"
          KeySchema:
            - AttributeName: "email"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"

#Outputs:
#  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
#  # Find out more about other implicit resources you can reference within SAM
#  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
#  HelloWorldApi:
#    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
#    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
#  HelloWorldFunction:
#    Description: "Hello World Lambda Function ARN"
#    Value: !GetAtt HelloWorldFunction.Arn
#  HelloWorldFunctionIamRole:
#    Description: "Implicit IAM Role created for Hello World function"
#    Value: !GetAtt HelloWorldFunctionRole.Arn